name: Update

on:
  workflow_dispatch:
  push:

jobs:
  update-docs:
    name: Build Scripts and Update Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21

      - name: Create Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.DYGNITORZ_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Issue test',
              body: '# Header\n\n- List item\n- List item\n\n## Subheader\n\n```js\nconst test = "test";\n```'
            })

      - name: Install dependencies
        run: bun install

      - name: Generate Scripts
        run: bun run index.ts

      - name: Generate Readme
        run: bun run readme.ts

      - name: Commit changes
        run: |
          git config --local user.email "${{ secrets.DYGNITORZ_EMAIL }}"
          git config --local user.name "${{ secrets.DYGNITORZ_NAME }}"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DYGNITORZ_TOKEN }}
          branch: ${{ github.ref_name }}
